// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8cUz0vbuehtj44V-_TCp9GfkcGaPNcuc',
    appId: '1:289113858512:web:2b0b581ee74d3745f959d5',
    messagingSenderId: '289113858512',
    projectId: 'class22-ff934',
    authDomain: 'class22-ff934.firebaseapp.com',
    storageBucket: 'class22-ff934.appspot.com',
    measurementId: 'G-FV4Q4M90JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEgpch8-kXB9gOfC4tubzrRU2f-fPaks',
    appId: '1:289113858512:android:4134672bce62c25ef959d5',
    messagingSenderId: '289113858512',
    projectId: 'class22-ff934',
    storageBucket: 'class22-ff934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm7JjyxxNtW-RTw9J8iTNfQbsuK1pbAXI',
    appId: '1:289113858512:ios:4dcbe2006e03483ef959d5',
    messagingSenderId: '289113858512',
    projectId: 'class22-ff934',
    storageBucket: 'class22-ff934.appspot.com',
    iosClientId: '289113858512-11jnivhbtob7k16vji63tkrk44ar9829.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm7JjyxxNtW-RTw9J8iTNfQbsuK1pbAXI',
    appId: '1:289113858512:ios:28cb98ff0c149c2bf959d5',
    messagingSenderId: '289113858512',
    projectId: 'class22-ff934',
    storageBucket: 'class22-ff934.appspot.com',
    iosClientId: '289113858512-fidabeehjkfj845uplmo4k95j07fsivc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
