// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYXw-PGT1mjhNq3VjFLq-DzUX6LtIqrOc',
    appId: '1:348071143847:web:16113cd9ca0c45d30fae82',
    messagingSenderId: '348071143847',
    projectId: 'news-18bb4',
    authDomain: 'news-18bb4.firebaseapp.com',
    storageBucket: 'news-18bb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRZBFDvsaS0A2Z97Laz-gxp_Y8u8bWxuc',
    appId: '1:348071143847:android:baa4c3e432b2df820fae82',
    messagingSenderId: '348071143847',
    projectId: 'news-18bb4',
    storageBucket: 'news-18bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwaWVrMK_o3KUpuAjNneVHKcjdsy9uTi4',
    appId: '1:348071143847:ios:b1fbe123e4a533ba0fae82',
    messagingSenderId: '348071143847',
    projectId: 'news-18bb4',
    storageBucket: 'news-18bb4.appspot.com',
    iosClientId: '348071143847-811h34fhaog3uac8cb6tu8aentmljsfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.newspaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwaWVrMK_o3KUpuAjNneVHKcjdsy9uTi4',
    appId: '1:348071143847:ios:5f3fb4dd87b6adb60fae82',
    messagingSenderId: '348071143847',
    projectId: 'news-18bb4',
    storageBucket: 'news-18bb4.appspot.com',
    iosClientId: '348071143847-0jd7b58fd3ji8toqd03qnbt12nb5afcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newspaper.RunnerTests',
  );
}
